"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
This is copied and lightly edited from
github.com/prometheus/client_model/io/prometheus/client/metrics.proto
and finally converted to proto3 syntax to make it usable for the
gogo-protobuf approach taken within prometheus/prometheus.
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.timestamp_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _MetricType:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _MetricTypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_MetricType.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    COUNTER: _MetricType.ValueType  # 0
    """COUNTER must use the Metric field "counter"."""
    GAUGE: _MetricType.ValueType  # 1
    """GAUGE must use the Metric field "gauge"."""
    SUMMARY: _MetricType.ValueType  # 2
    """SUMMARY must use the Metric field "summary"."""
    UNTYPED: _MetricType.ValueType  # 3
    """UNTYPED must use the Metric field "untyped"."""
    HISTOGRAM: _MetricType.ValueType  # 4
    """HISTOGRAM must use the Metric field "histogram"."""
    GAUGE_HISTOGRAM: _MetricType.ValueType  # 5
    """GAUGE_HISTOGRAM must use the Metric field "histogram"."""

class MetricType(_MetricType, metaclass=_MetricTypeEnumTypeWrapper): ...

COUNTER: MetricType.ValueType  # 0
"""COUNTER must use the Metric field "counter"."""
GAUGE: MetricType.ValueType  # 1
"""GAUGE must use the Metric field "gauge"."""
SUMMARY: MetricType.ValueType  # 2
"""SUMMARY must use the Metric field "summary"."""
UNTYPED: MetricType.ValueType  # 3
"""UNTYPED must use the Metric field "untyped"."""
HISTOGRAM: MetricType.ValueType  # 4
"""HISTOGRAM must use the Metric field "histogram"."""
GAUGE_HISTOGRAM: MetricType.ValueType  # 5
"""GAUGE_HISTOGRAM must use the Metric field "histogram"."""
global___MetricType = MetricType

@typing.final
class LabelPair(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    name: builtins.str
    value: builtins.str
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        value: builtins.str | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["name", b"name", "value", b"value"]) -> None: ...

global___LabelPair = LabelPair

@typing.final
class Gauge(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.float
    def __init__(
        self,
        *,
        value: builtins.float | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___Gauge = Gauge

@typing.final
class Counter(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    EXEMPLAR_FIELD_NUMBER: builtins.int
    CREATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    value: builtins.float
    @property
    def exemplar(self) -> global___Exemplar: ...
    @property
    def created_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        value: builtins.float | None = ...,
        exemplar: global___Exemplar | None = ...,
        created_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_timestamp", b"created_timestamp", "exemplar", b"exemplar"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_timestamp", b"created_timestamp", "exemplar", b"exemplar", "value", b"value"]) -> None: ...

global___Counter = Counter

@typing.final
class Quantile(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    QUANTILE_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    quantile: builtins.float
    value: builtins.float
    def __init__(
        self,
        *,
        quantile: builtins.float | None = ...,
        value: builtins.float | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["quantile", b"quantile", "value", b"value"]) -> None: ...

global___Quantile = Quantile

@typing.final
class Summary(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAMPLE_COUNT_FIELD_NUMBER: builtins.int
    SAMPLE_SUM_FIELD_NUMBER: builtins.int
    QUANTILE_FIELD_NUMBER: builtins.int
    CREATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    sample_count: builtins.int
    sample_sum: builtins.float
    @property
    def quantile(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Quantile]: ...
    @property
    def created_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        sample_count: builtins.int | None = ...,
        sample_sum: builtins.float | None = ...,
        quantile: collections.abc.Iterable[global___Quantile] | None = ...,
        created_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_timestamp", b"created_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["created_timestamp", b"created_timestamp", "quantile", b"quantile", "sample_count", b"sample_count", "sample_sum", b"sample_sum"]) -> None: ...

global___Summary = Summary

@typing.final
class Untyped(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VALUE_FIELD_NUMBER: builtins.int
    value: builtins.float
    def __init__(
        self,
        *,
        value: builtins.float | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["value", b"value"]) -> None: ...

global___Untyped = Untyped

@typing.final
class Histogram(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SAMPLE_COUNT_FIELD_NUMBER: builtins.int
    SAMPLE_COUNT_FLOAT_FIELD_NUMBER: builtins.int
    SAMPLE_SUM_FIELD_NUMBER: builtins.int
    BUCKET_FIELD_NUMBER: builtins.int
    CREATED_TIMESTAMP_FIELD_NUMBER: builtins.int
    SCHEMA_FIELD_NUMBER: builtins.int
    ZERO_THRESHOLD_FIELD_NUMBER: builtins.int
    ZERO_COUNT_FIELD_NUMBER: builtins.int
    ZERO_COUNT_FLOAT_FIELD_NUMBER: builtins.int
    NEGATIVE_SPAN_FIELD_NUMBER: builtins.int
    NEGATIVE_DELTA_FIELD_NUMBER: builtins.int
    NEGATIVE_COUNT_FIELD_NUMBER: builtins.int
    POSITIVE_SPAN_FIELD_NUMBER: builtins.int
    POSITIVE_DELTA_FIELD_NUMBER: builtins.int
    POSITIVE_COUNT_FIELD_NUMBER: builtins.int
    EXEMPLARS_FIELD_NUMBER: builtins.int
    sample_count: builtins.int
    sample_count_float: builtins.float
    """Overrides sample_count if > 0."""
    sample_sum: builtins.float
    schema: builtins.int
    """Everything below here is for native histograms (also known as sparse histograms).
    Native histograms are an experimental feature without stability guarantees.

    schema defines the bucket schema. Currently, valid numbers are -4 <= n <= 8.
    They are all for base-2 bucket schemas, where 1 is a bucket boundary in each case, and
    then each power of two is divided into 2^n logarithmic buckets.
    Or in other words, each bucket boundary is the previous boundary times 2^(2^-n).
    In the future, more bucket schemas may be added using numbers < -4 or > 8.
    """
    zero_threshold: builtins.float
    """Breadth of the zero bucket."""
    zero_count: builtins.int
    """Count in zero bucket."""
    zero_count_float: builtins.float
    """Overrides sb_zero_count if > 0."""
    @property
    def bucket(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Bucket]:
        """Buckets for the classic histogram.
        Ordered in increasing order of upper_bound, +Inf bucket is optional.
        """

    @property
    def created_timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp: ...
    @property
    def negative_span(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BucketSpan]:
        """Negative buckets for the native histogram."""

    @property
    def negative_delta(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Use either "negative_delta" or "negative_count", the former for
        regular histograms with integer counts, the latter for float
        histograms.
        Count delta of each bucket compared to previous one (or to zero for 1st bucket).
        """

    @property
    def negative_count(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Absolute count of each bucket."""

    @property
    def positive_span(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___BucketSpan]:
        """Positive buckets for the native histogram.
        Use a no-op span (offset 0, length 0) for a native histogram without any
        observations yet and with a zero_threshold of 0. Otherwise, it would be
        indistinguishable from a classic histogram.
        """

    @property
    def positive_delta(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.int]:
        """Use either "positive_delta" or "positive_count", the former for
        regular histograms with integer counts, the latter for float
        histograms.
        Count delta of each bucket compared to previous one (or to zero for 1st bucket).
        """

    @property
    def positive_count(self) -> google.protobuf.internal.containers.RepeatedScalarFieldContainer[builtins.float]:
        """Absolute count of each bucket."""

    @property
    def exemplars(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Exemplar]:
        """Only used for native histograms. These exemplars MUST have a timestamp."""

    def __init__(
        self,
        *,
        sample_count: builtins.int | None = ...,
        sample_count_float: builtins.float | None = ...,
        sample_sum: builtins.float | None = ...,
        bucket: collections.abc.Iterable[global___Bucket] | None = ...,
        created_timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
        schema: builtins.int | None = ...,
        zero_threshold: builtins.float | None = ...,
        zero_count: builtins.int | None = ...,
        zero_count_float: builtins.float | None = ...,
        negative_span: collections.abc.Iterable[global___BucketSpan] | None = ...,
        negative_delta: collections.abc.Iterable[builtins.int] | None = ...,
        negative_count: collections.abc.Iterable[builtins.float] | None = ...,
        positive_span: collections.abc.Iterable[global___BucketSpan] | None = ...,
        positive_delta: collections.abc.Iterable[builtins.int] | None = ...,
        positive_count: collections.abc.Iterable[builtins.float] | None = ...,
        exemplars: collections.abc.Iterable[global___Exemplar] | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["created_timestamp", b"created_timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["bucket", b"bucket", "created_timestamp", b"created_timestamp", "exemplars", b"exemplars", "negative_count", b"negative_count", "negative_delta", b"negative_delta", "negative_span", b"negative_span", "positive_count", b"positive_count", "positive_delta", b"positive_delta", "positive_span", b"positive_span", "sample_count", b"sample_count", "sample_count_float", b"sample_count_float", "sample_sum", b"sample_sum", "schema", b"schema", "zero_count", b"zero_count", "zero_count_float", b"zero_count_float", "zero_threshold", b"zero_threshold"]) -> None: ...

global___Histogram = Histogram

@typing.final
class Bucket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CUMULATIVE_COUNT_FIELD_NUMBER: builtins.int
    CUMULATIVE_COUNT_FLOAT_FIELD_NUMBER: builtins.int
    UPPER_BOUND_FIELD_NUMBER: builtins.int
    EXEMPLAR_FIELD_NUMBER: builtins.int
    cumulative_count: builtins.int
    """Cumulative in increasing order."""
    cumulative_count_float: builtins.float
    """Overrides cumulative_count if > 0."""
    upper_bound: builtins.float
    """Inclusive."""
    @property
    def exemplar(self) -> global___Exemplar: ...
    def __init__(
        self,
        *,
        cumulative_count: builtins.int | None = ...,
        cumulative_count_float: builtins.float | None = ...,
        upper_bound: builtins.float | None = ...,
        exemplar: global___Exemplar | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["exemplar", b"exemplar"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["cumulative_count", b"cumulative_count", "cumulative_count_float", b"cumulative_count_float", "exemplar", b"exemplar", "upper_bound", b"upper_bound"]) -> None: ...

global___Bucket = Bucket

@typing.final
class BucketSpan(google.protobuf.message.Message):
    """A BucketSpan defines a number of consecutive buckets in a native
    histogram with their offset. Logically, it would be more
    straightforward to include the bucket counts in the Span. However,
    the protobuf representation is more compact in the way the data is
    structured here (with all the buckets in a single array separate
    from the Spans).
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    OFFSET_FIELD_NUMBER: builtins.int
    LENGTH_FIELD_NUMBER: builtins.int
    offset: builtins.int
    """Gap to previous span, or starting point for 1st span (which can be negative)."""
    length: builtins.int
    """Length of consecutive buckets."""
    def __init__(
        self,
        *,
        offset: builtins.int | None = ...,
        length: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["length", b"length", "offset", b"offset"]) -> None: ...

global___BucketSpan = BucketSpan

@typing.final
class Exemplar(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LABEL_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    TIMESTAMP_FIELD_NUMBER: builtins.int
    value: builtins.float
    @property
    def label(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LabelPair]: ...
    @property
    def timestamp(self) -> google.protobuf.timestamp_pb2.Timestamp:
        """OpenMetrics-style."""

    def __init__(
        self,
        *,
        label: collections.abc.Iterable[global___LabelPair] | None = ...,
        value: builtins.float | None = ...,
        timestamp: google.protobuf.timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["timestamp", b"timestamp"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["label", b"label", "timestamp", b"timestamp", "value", b"value"]) -> None: ...

global___Exemplar = Exemplar

@typing.final
class Metric(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LABEL_FIELD_NUMBER: builtins.int
    GAUGE_FIELD_NUMBER: builtins.int
    COUNTER_FIELD_NUMBER: builtins.int
    SUMMARY_FIELD_NUMBER: builtins.int
    UNTYPED_FIELD_NUMBER: builtins.int
    HISTOGRAM_FIELD_NUMBER: builtins.int
    TIMESTAMP_MS_FIELD_NUMBER: builtins.int
    timestamp_ms: builtins.int
    @property
    def label(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LabelPair]: ...
    @property
    def gauge(self) -> global___Gauge: ...
    @property
    def counter(self) -> global___Counter: ...
    @property
    def summary(self) -> global___Summary: ...
    @property
    def untyped(self) -> global___Untyped: ...
    @property
    def histogram(self) -> global___Histogram: ...
    def __init__(
        self,
        *,
        label: collections.abc.Iterable[global___LabelPair] | None = ...,
        gauge: global___Gauge | None = ...,
        counter: global___Counter | None = ...,
        summary: global___Summary | None = ...,
        untyped: global___Untyped | None = ...,
        histogram: global___Histogram | None = ...,
        timestamp_ms: builtins.int | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["counter", b"counter", "gauge", b"gauge", "histogram", b"histogram", "summary", b"summary", "untyped", b"untyped"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["counter", b"counter", "gauge", b"gauge", "histogram", b"histogram", "label", b"label", "summary", b"summary", "timestamp_ms", b"timestamp_ms", "untyped", b"untyped"]) -> None: ...

global___Metric = Metric

@typing.final
class MetricFamily(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NAME_FIELD_NUMBER: builtins.int
    HELP_FIELD_NUMBER: builtins.int
    TYPE_FIELD_NUMBER: builtins.int
    METRIC_FIELD_NUMBER: builtins.int
    UNIT_FIELD_NUMBER: builtins.int
    name: builtins.str
    help: builtins.str
    type: global___MetricType.ValueType
    unit: builtins.str
    @property
    def metric(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Metric]: ...
    def __init__(
        self,
        *,
        name: builtins.str | None = ...,
        help: builtins.str | None = ...,
        type: global___MetricType.ValueType | None = ...,
        metric: collections.abc.Iterable[global___Metric] | None = ...,
        unit: builtins.str | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["help", b"help", "metric", b"metric", "name", b"name", "type", b"type", "unit", b"unit"]) -> None: ...

global___MetricFamily = MetricFamily
